export interface PermissionDef {
  key: string;
  label: string;
  group: string;
}

/**
 * The full catalogue of assignable permissions — one read key per resource
 * plus one key per write endpoint. Generated to match the @RequirePermissions
 * decorators on the controllers. Admin holds all of them.
 */
export const PERMISSIONS: PermissionDef[] = [
  { key: 'attachments:read', label: 'Read', group: 'Attachments' },
  { key: 'attachments:create', label: 'Create', group: 'Attachments' },
  { key: 'attachments:delete', label: 'Delete', group: 'Attachments' },
  { key: 'audit:view', label: 'View', group: 'Audit' },
  { key: 'contacts:read', label: 'Read', group: 'Contacts' },
  { key: 'contacts:create', label: 'Create', group: 'Contacts' },
  { key: 'contacts:update', label: 'Update', group: 'Contacts' },
  { key: 'contacts:delete', label: 'Delete', group: 'Contacts' },
  { key: 'customers:read', label: 'Read', group: 'Customers' },
  { key: 'customers:create', label: 'Create', group: 'Customers' },
  { key: 'customers:update', label: 'Update', group: 'Customers' },
  { key: 'customers:delete', label: 'Delete', group: 'Customers' },
  {
    key: 'inventory-balances:read',
    label: 'Read',
    group: 'Inventory Balances',
  },
  { key: 'stock-items:read', label: 'Read', group: 'Stock Items' },
  { key: 'stock-items:create', label: 'Create', group: 'Stock Items' },
  { key: 'stock-items:update', label: 'Update', group: 'Stock Items' },
  {
    key: 'stock-items:create-reserve',
    label: 'Create Reserve',
    group: 'Stock Items',
  },
  {
    key: 'stock-items:create-release',
    label: 'Create Release',
    group: 'Stock Items',
  },
  {
    key: 'stock-items:create-consume',
    label: 'Create Consume',
    group: 'Stock Items',
  },
  {
    key: 'stock-items:confirm-reserve',
    label: 'Confirm Reserve',
    group: 'Stock Items',
  },
  { key: 'stock-items:deliver', label: 'Deliver', group: 'Stock Items' },
  {
    key: 'stock-items:receive-return',
    label: 'Receive Return',
    group: 'Stock Items',
  },
  { key: 'stock-items:delete', label: 'Delete', group: 'Stock Items' },
  {
    key: 'inventory-transactions:read',
    label: 'Read',
    group: 'Inventory Transactions',
  },
  {
    key: 'inventory-transactions:create',
    label: 'Create',
    group: 'Inventory Transactions',
  },
  {
    key: 'inventory-transactions:create-adjust',
    label: 'Create Adjust',
    group: 'Inventory Transactions',
  },
  {
    key: 'inventory-transactions:create-issue',
    label: 'Create Issue',
    group: 'Inventory Transactions',
  },
  {
    key: 'inventory-transactions:create-receive',
    label: 'Create Receive',
    group: 'Inventory Transactions',
  },
  {
    key: 'inventory-transactions:create-transfer',
    label: 'Create Transfer',
    group: 'Inventory Transactions',
  },
  {
    key: 'inventory-transactions:create-reverse',
    label: 'Create Reverse',
    group: 'Inventory Transactions',
  },
  { key: 'location-data:read', label: 'Read', group: 'Location Data' },
  { key: 'location-data:create', label: 'Create', group: 'Location Data' },
  { key: 'location-data:delete', label: 'Delete', group: 'Location Data' },
  { key: 'locations:read', label: 'Read', group: 'Locations' },
  { key: 'locations:create', label: 'Create', group: 'Locations' },
  { key: 'locations:update', label: 'Update', group: 'Locations' },
  { key: 'locations:delete', label: 'Delete', group: 'Locations' },
  { key: 'lots:read', label: 'Read', group: 'Lots' },
  { key: 'lots:create', label: 'Create', group: 'Lots' },
  { key: 'lots:update', label: 'Update', group: 'Lots' },
  { key: 'lots:delete', label: 'Delete', group: 'Lots' },
  { key: 'material-types:read', label: 'Read', group: 'Material Types' },
  { key: 'material-types:create', label: 'Create', group: 'Material Types' },
  { key: 'material-types:update', label: 'Update', group: 'Material Types' },
  { key: 'material-types:delete', label: 'Delete', group: 'Material Types' },
  { key: 'material-units:read', label: 'Read', group: 'Material Units' },
  { key: 'material-units:create', label: 'Create', group: 'Material Units' },
  { key: 'material-units:update', label: 'Update', group: 'Material Units' },
  { key: 'material-units:delete', label: 'Delete', group: 'Material Units' },
  { key: 'materials:read', label: 'Read', group: 'Materials' },
  { key: 'materials:create', label: 'Create', group: 'Materials' },
  { key: 'materials:update', label: 'Update', group: 'Materials' },
  { key: 'materials:delete', label: 'Delete', group: 'Materials' },
  { key: 'order-items:read', label: 'Read', group: 'Order Items' },
  { key: 'order-items:create', label: 'Create', group: 'Order Items' },
  { key: 'order-items:update', label: 'Update', group: 'Order Items' },
  { key: 'order-items:delete', label: 'Delete', group: 'Order Items' },
  { key: 'orders:read', label: 'Read', group: 'Orders' },
  { key: 'orders:create', label: 'Create', group: 'Orders' },
  { key: 'orders:delete', label: 'Delete', group: 'Orders' },
  { key: 'process-stages:read', label: 'Read', group: 'Process Stages' },
  // NOTE: structural stage editing (add/edit/connect/reorder/delete stages)
  // is NOT permission-key based — those routes authorize in the service as
  // "process responsible or admin".
  // NOTE: stage STATUS changes are also relationship-based (admin/process
  // responsible = any transition; stage worker = start/complete only) — no
  // permission key.
  { key: 'process-stages:update', label: 'Update', group: 'Process Stages' },
  {
    key: 'process-stages:reserve-tools',
    label: 'Reserve Tools',
    group: 'Process Stages',
  },
  { key: 'processes:read', label: 'Read', group: 'Processes' },
  { key: 'processes:create', label: 'Create', group: 'Processes' },
  {
    key: 'processes:update',
    label: 'Update (assign responsible)',
    group: 'Processes',
  },
  { key: 'processes:delete', label: 'Delete', group: 'Processes' },
  { key: 'workload:read', label: 'Read (org-wide Gantt)', group: 'Processes' },
  { key: 'product-types:read', label: 'Read', group: 'Product Types' },
  { key: 'product-types:create', label: 'Create', group: 'Product Types' },
  { key: 'product-types:update', label: 'Update', group: 'Product Types' },
  { key: 'product-types:delete', label: 'Delete', group: 'Product Types' },
  { key: 'products:read', label: 'Read', group: 'Products' },
  { key: 'products:create', label: 'Create', group: 'Products' },
  { key: 'products:update', label: 'Update', group: 'Products' },
  { key: 'products:delete', label: 'Delete', group: 'Products' },
  {
    key: 'products:consume',
    label: 'Consume (use as stage input)',
    group: 'Products',
  },
  { key: 'projects:read', label: 'Read', group: 'Projects' },
  { key: 'projects:create', label: 'Create', group: 'Projects' },
  { key: 'projects:update', label: 'Update', group: 'Projects' },
  { key: 'projects:delete', label: 'Delete', group: 'Projects' },
  {
    key: 'projects:manage-members',
    label: 'Manage Team (assign users)',
    group: 'Projects',
  },
  {
    key: 'projects:manage-contacts',
    label: 'Manage Contacts (attach customer contacts)',
    group: 'Projects',
  },
  { key: 'racks:read', label: 'Read', group: 'Racks' },
  { key: 'racks:create', label: 'Create', group: 'Racks' },
  { key: 'racks:update', label: 'Update', group: 'Racks' },
  { key: 'racks:delete', label: 'Delete', group: 'Racks' },
  // Racks of a LOCATION's storage area (location module) — separate from the
  // inventory racks above.
  { key: 'storage-racks:read', label: 'Read', group: 'Storage Racks' },
  { key: 'storage-racks:create', label: 'Create', group: 'Storage Racks' },
  { key: 'storage-racks:update', label: 'Update', group: 'Storage Racks' },
  { key: 'storage-racks:delete', label: 'Delete', group: 'Storage Racks' },
  { key: 'reports:read', label: 'Read', group: 'Reports' },
  { key: 'reports:create', label: 'Create', group: 'Reports' },
  { key: 'reports:update', label: 'Update', group: 'Reports' },
  { key: 'reports:delete', label: 'Delete', group: 'Reports' },
  { key: 'reports:generate', label: 'Generate', group: 'Reports' },
  { key: 'roles:read', label: 'Read', group: 'Roles' },
  { key: 'roles:create', label: 'Create', group: 'Roles' },
  { key: 'roles:update', label: 'Update', group: 'Roles' },
  {
    key: 'roles:update-permissions',
    label: 'Update Permissions',
    group: 'Roles',
  },
  { key: 'roles:delete', label: 'Delete', group: 'Roles' },
  {
    key: 'section-reservations:read',
    label: 'Read',
    group: 'Section Reservations',
  },
  {
    key: 'section-reservations:create',
    label: 'Create',
    group: 'Section Reservations',
  },
  {
    key: 'section-reservations:update',
    label: 'Update',
    group: 'Section Reservations',
  },
  {
    key: 'section-reservations:delete',
    label: 'Delete',
    group: 'Section Reservations',
  },
  { key: 'sections:read', label: 'Read', group: 'Sections' },
  { key: 'sections:create', label: 'Create', group: 'Sections' },
  { key: 'sections:update', label: 'Update', group: 'Sections' },
  { key: 'sections:delete', label: 'Delete', group: 'Sections' },
  {
    key: 'stage-type-categories:read',
    label: 'Read',
    group: 'Stage Type Categories',
  },
  {
    key: 'stage-type-categories:create',
    label: 'Create',
    group: 'Stage Type Categories',
  },
  {
    key: 'stage-type-categories:update',
    label: 'Update',
    group: 'Stage Type Categories',
  },
  {
    key: 'stage-type-categories:delete',
    label: 'Delete',
    group: 'Stage Type Categories',
  },
  { key: 'stage-types:read', label: 'Read', group: 'Stage Types' },
  { key: 'stage-types:create', label: 'Create', group: 'Stage Types' },
  { key: 'stage-types:update', label: 'Update', group: 'Stage Types' },
  { key: 'stage-types:delete', label: 'Delete', group: 'Stage Types' },
  { key: 'tool-assignments:read', label: 'Read', group: 'Tool Assignments' },
  { key: 'tool-cycle-logs:read', label: 'Read', group: 'Tool Cycle Logs' },
  {
    key: 'tool-status-history:read',
    label: 'Read',
    group: 'Tool Status History',
  },
  { key: 'tool-types:read', label: 'Read', group: 'Tool Types' },
  { key: 'tool-types:create', label: 'Create', group: 'Tool Types' },
  { key: 'tool-types:update', label: 'Update', group: 'Tool Types' },
  { key: 'tool-types:delete', label: 'Delete', group: 'Tool Types' },
  { key: 'tool-usages:read', label: 'Read', group: 'Tool Usages' },
  { key: 'tools:read', label: 'Read', group: 'Tools' },
  { key: 'tools:create', label: 'Create', group: 'Tools' },
  { key: 'tools:create-assign', label: 'Create Assign', group: 'Tools' },
  { key: 'tools:create-cycles', label: 'Create Cycles', group: 'Tools' },
  { key: 'tools:create-end', label: 'Create End', group: 'Tools' },
  { key: 'tools:create-reset', label: 'Create Reset', group: 'Tools' },
  { key: 'tools:create-return', label: 'Create Return', group: 'Tools' },
  { key: 'tools:create-start', label: 'Create Start', group: 'Tools' },
  { key: 'tools:handover', label: 'Handover', group: 'Tools' },
  { key: 'tools:update', label: 'Update', group: 'Tools' },
  { key: 'tools:update-status', label: 'Update Status', group: 'Tools' },
  { key: 'tools:delete', label: 'Delete', group: 'Tools' },
  { key: 'users:read', label: 'Read', group: 'Users' },
  { key: 'users:update', label: 'Update', group: 'Users' },
  { key: 'users:delete', label: 'Delete', group: 'Users' },
  { key: 'warehouses:read', label: 'Read', group: 'Warehouses' },
  { key: 'warehouses:create', label: 'Create', group: 'Warehouses' },
  { key: 'warehouses:update', label: 'Update', group: 'Warehouses' },
  { key: 'warehouses:delete', label: 'Delete', group: 'Warehouses' },
  {
    key: 'workflow-templates:read',
    label: 'Read',
    group: 'Workflow Templates',
  },
  {
    key: 'workflow-templates:create',
    label: 'Create',
    group: 'Workflow Templates',
  },
  {
    key: 'workflow-templates:create-duplicate',
    label: 'Create Duplicate',
    group: 'Workflow Templates',
  },
  {
    key: 'workflow-templates:update',
    label: 'Update',
    group: 'Workflow Templates',
  },
  {
    key: 'workflow-templates:delete',
    label: 'Delete',
    group: 'Workflow Templates',
  },
  { key: 'zones:read', label: 'Read', group: 'Zones' },
  { key: 'zones:create', label: 'Create', group: 'Zones' },
  { key: 'zones:update', label: 'Update', group: 'Zones' },
  { key: 'zones:delete', label: 'Delete', group: 'Zones' },
];

export const PERMISSION_KEYS: string[] = PERMISSIONS.map((p) => p.key);
