import {
  IsDateString,
  IsOptional,
  IsString,
  IsUUID,
  Matches,
  MaxLength,
  MinLength,
} from 'class-validator';

export class CreateLotDto {
  // Auto-generated by the server (LOT-YYYYMMDD-NNNN). Optional + ignored if a
  // client still sends one — the lot number is never client-set.
  @IsOptional()
  @IsString()
  @MinLength(1)
  @MaxLength(50)
  @Matches(/^[A-Za-z0-9][A-Za-z0-9_./-]*$/, {
    message: 'lotNumber must be alphanumeric (letters, digits, . / - _)',
  })
  lotNumber?: string;

  @IsUUID()
  materialId: string;

  @IsOptional()
  @IsUUID()
  rackId?: string | null;

  @IsOptional()
  @IsUUID()
  customerId?: string | null;

  @IsOptional()
  @IsUUID()
  projectId?: string | null;

  @IsOptional()
  @IsDateString()
  expiryDate?: string;
}
